POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam",
  "name": "Adam Richard",
  "password": "rich",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richa",
  "password": "richard_567"
}
###