POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Balu",
  "name": "Balu Kotthuru",
  "password": "Balu@143",
  "gender": "male",
  "location": "India"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richa",
  "password": "richard_567"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "Balu",
  "oldPassword": "Balu@143",
  "newPassword": "Balu@123"
}
###
